Exercicio 1: 
============
base de dados
Pede-se:

1) utilize a lib correta para ler dados do CSV
2) crie uma variavel do tipo DataFrame para receber os dados lidos pela lib que lê CSV
3) faça exibir os dados na tela

In [1]:
import pandas as pd
import locale

local_arquivo = r'C:\Rafaélla Sena - Python\Python 2\Python 2 - Clarify\Aluno\Aula_01\Exercicios\exportacoes_franca.csv'
dados = pd.read_csv(local_arquivo, sep=',')

display(dados)

def formatar(valor):
    locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

Exercicio 2
===========
Como foi a evolução das exportações para a frança ao longo dos anos?

Crie uma tabela com os anos:
    2016,
    2017,
    2018,
    2019,
    2020 
e o valor US$ de exportações

1) faça um agrupamento por ano e some "US$ FOB"
2) formate os valores da coluna "US$ FOB" em US$
3) exibir os resultados anuais totais

In [ ]:
def formatar(valor):
    valor_formatado = f' US$ {valor:,}'
    return valor_formatado

faturamento_por_plano = dados.groupby('Year').sum('US$ FOB')
faturamento_por_plano = faturamento_por_plano[['US$ FOB']]

faturamento_por_plano['US$ FOB'] = faturamento_por_plano ['US$ FOB'].apply(formatar)

display(faturamento_por_plano)

                 US$ FOB
Year
2016   US$ 4,615,500,082
2017   US$ 4,448,705,456
2018   US$ 5,239,424,416
2019   US$ 5,218,723,612
2020   US$ 3,967,594,810

Exercicio 3
===========
Quais os produtos mais exportados ao longo de todo o período?

Queremos saber os produtos com maior valor US$ de exportação

1) Retorne as colunas: "SH2 Description", "US$ FOB" e agrupe por 
"SH2 Description", faça a soma da coluna de valor: "US$ FOB"

2) Classifique a coluna de valor: "US$ FOB" do maior para o menor [Z-A]

3) Exibir os dados

In [ ]:

produto_por_valor = dados[['SH2 Description','US$ FOB']].groupby('SH2 Description').sum()
produto_por_valor = produto_por_valor.sort_values(by='US$ FOB', ascending=False)

faturamento_por_plano["US$ FOB"] = faturamento_por_plano ["US$ FOB"].apply(formatar)

display(produto_por_valor)

ValueError: Cannot specify ',' with 's'.

Exercicio 4
===========
Em 2020 qual cidade mais exportou para a França?
Em valores US$

1) Filtre o Ano:    tabela.loc[tabela["Year"]==2020]
2) retorne as colunas: "City" e "US$ FOB", faça o agrupamento por "City" e some "US$ FOB"
3) Classifique a coluna de valor: "US$ FOB" do maior para o menor [Z-A]
4) Exibir os resultados

Exercicio 5
===========
Quais os produtos mais exportados (em US$) que as 2 maiores cidades (em exportação em 2020) exportaram?